import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex-1 overflow-y-auto relative flex flex-col min-w-0 pt-16 lg:pt-0`}
      >
        <div className="flex-1 w-full max-w-7xl mx-auto p-4 md:p-8 flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
